version: "3"
services:
    mosquitto:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: dininfo1
        volumes:
            - data:/var/lib/postgresql/data
    server:
        image: magida/iot-server
        ports:
            - "80:5000"
        

volumes:
    data:
        driver: local